### ISSUE TITLE
Topics returning null

### ISSUE THREAD

**Issue by tkserver** [ePascalC/bbp-API#2]
wp-json/bbp-api/v1/topics is returning null for me

**Comment by ePascalC** [comment]
Hi tkserver,
I'm busy for WCEU this week, so let me have a look how far I was with those topics next week.
Pascal.

**Comment by ePascalC** [comment]
Check out /wp-json/bbp-api/v1/forums/ID  (where ID is the forum ID). You will find the topics there.
