### ISSUE TITLE
Next page is empty

### ISSUE THREAD

**Issue by ePascalC** [ePascalC/bbp-API#22]
If the number of topics is exactly the number set in the per_page, the API indicates there is a next page, but in fact there is not.

**Comment by tkserver** [comment]
I think this is still an issue in 1.0.13 because the total_replies is +1 more than it should be.  So if there are 10 replies the API says there are 11, so the paging thinks there's a next page if per_page=10.

**Comment by ePascalC** [comment]
You are correct, for the replies there is still the issue :-(
But working on it!

**Comment by ePascalC** [comment]
Fixed in v1.0.14
