### ISSUE TITLE
How can i Add New API in your Plugin

### ISSUE THREAD

**Issue by anuragjainsagar** [ePascalC/bbp-API#3]
i wants to add some other information in your API so i was trying to create function for different kind of use. but when i add a function and write the function it gives same error that "No route was found matching the URL and request method".

Can you please suggest how i can make this.

**Comment by ePascalC** [comment]
Hi,
Thanks! Any contribution is welcome.
What I have done so far comes straight out of the REST-API handbook. I would suggest to read e.g. https://developer.wordpress.org/rest-api/extending-the-rest-api/adding-custom-endpoints/.
Keep me informed!
Pascal.
