### ISSUE TITLE
Add sort order to forums

### ISSUE THREAD

**Issue by tkserver** [ePascalC/bbp-API#34]
We can sort the forums in bbpress via the order field under edit forum.  It would be nice if that order number came through the api so the forums could be ordered in the result as preferred by the forum order setting of the site.  

Interestingly, the api outputs the forum list in the order set by the order field though.

**Comment by ePascalC** [comment]
As you indicate yourself, the API already outputs them in order (for most of the forums, the sort will be equal to 0).
So what would be the added value in adding this to the API?
