### ISSUE TITLE
Content missing when outputting a list of topics

### ISSUE THREAD

**Issue by renatonascalves** [ePascalC/bbp-API#36]
There are a lot more information from the topic object that is not being outputted when using `wp-json/bbp-api/v1/topics`

I'm gonna prepare a Pull Request to fetch those missing content, here is a small list:

- [x] date
- [x] date_gmt
- [x] guid
- [x] status
- [x] content
- [x] author ID (The fix for this one is [here](https://github.com/ePascalC/bbp-API/pull/39)) 

Etc. The plan is to align the fields with the ones outputted by the posts: `wp-json/wp/v2/posts`

**Comment by tkserver** [comment]
Date is not missing. Look for post_date

**Comment by tkserver** [comment]
I think guid is probably just id in the api.  I disagree with having the content in the list of topics. That will slow down the query big time, and make the object much larger.  Maybe an _embedded option for that.

**Comment by renatonascalves** [comment]
Date - The date comes formated.
Date GMT - GMT based date is missing.

post_content - I fetch a list of topics and want to show a description or a portion of the content from the questions. Right now I can't.

I presume it'd get a bit slower but nothing so big.

**Comment by tkserver** [comment]
Yeah true on the date format. If it was epoch time or something that would be easier to customize. Perhaps you want the excerpt for your content.

**Comment by renatonascalves** [comment]
Nope! The content! Topics content are saved as `post_content`. I think we should output that information in the list of topics. 

If you pull `wp-json/wp/v2/posts`, you get all the information from the posts. If one wants to avoid some information from being show, we should add a filter so that one can remove it. But, by default, all information should be there.

**Comment by ePascalC** [comment]
I think aligning as much as possible to the 'posts' endpoint is a good idea!
For date, date_gmt, guid, status: I will add those
For author: I will have to group all the author info under one header. ID can be added as it's added for a post
For content: Content will be added by default HOWEVER I will allow a parameter to set to omit the content because for a lot of uses, the content will not be needed. But as I want to keep the standards, the default will be to show the content.

**Comment by tkserver** [comment]
Why not do the _embedded option for the content?

**Comment by renatonascalves** [comment]
@ePascalC Better yet, instead of filtering only the `post_content`, what about a global filter so that other fields might be removed as well?

**Comment by renatonascalves** [comment]
I created a PR with the proposed changes: https://github.com/ePascalC/bbp-API/pull/41
