### ISSUE TITLE
Add more information to author_avatar

### ISSUE THREAD

**Issue by renatonascalves** [ePascalC/bbp-API#38]
This is how I think it should be:

```
"author_avatar": {
    "width"      : 40,
    "height"     : 40,
    "source_url" : "https://site/wp-content/uploads/avatars/41/41-bpthumb.jpg",
    "html"       : "<img alt='' src='http://site/wp-content/uploads/avatars/41/41-bpthumb.jpg' srcset='http://site/wp-content/uploads/avatars/41/41-bpthumb.jpg 2x' class='avatar avatar-40 photo' height='40' width='40' />",
}
```

**Comment by tkserver** [comment]
I like this idea, except it will break my app when it is implemented.  :-(

**Comment by renatonascalves** [comment]
What about a `html` option? I updated my first comment with the proposed change.

The idea is to allow flexibility. Instead of deciding for the user, we give options and the developer can use however he likes. :)

**Comment by tkserver** [comment]
It will still break my app but yes, allowing the dev flexibility is the key.  That said, source_url and html are a wee bit redundant.

**Comment by renatonascalves** [comment]
Agree! That was just a suggestion! :)

I also would encourage you to think beyond your project. This plugin might land in bbPress core in the future and we need to think of other scenarios or allow more flexibility. :)

**Comment by renatonascalves** [comment]
I'll work on a PR for this change! :)

**Comment by tkserver** [comment]
> I also would encourage you to think beyond your project.
Yes of course, but that's how I'm learning/building the app via the bbp api.

**Comment by ePascalC** [comment]
All data need to be grouped under author, but please the redundant ones like html and file should be removed.
See also https://github.com/ePascalC/bbp-API/issues/36#issuecomment-330178482
